# Uncomment the next line to define a global platform for your project
  platform :ios, '9.0'
  use_frameworks!

target 'ARChemistry' do


    pod 'MBProgressHUD'
    pod 'SDWebImage'
    pod 'Alamofire', '4.5.1'
    pod 'ObjectMapper', '~> 3.1'

end
