# Uncomment the next line to define a global platform for your project
  platform :ios, '9.0'

target 'ARChemistry' do
    use_frameworks!	

    pod 'MBProgressHUD'
    pod 'SDWebImage'
    pod 'Alamofire', '4.5.1'
    pod 'ObjectMapper', '~> 3.1'
    pod 'Macaw', '0.9.2'
    pod 'TransitionButton'
    pod 'FacebookCore'
    pod 'FacebookLogin'
    pod 'Kingfisher', '~> 4.0'
    pod 'Firebase/Core'
    pod 'Firebase/Database'
    pod 'Firebase/Auth'
    pod 'Firebase/Storage'
    pod 'GoogleSignIn'

end
